name: GitHub Pages

on:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install Flatpak
      run: sudo apt-get install flatpak
    - name: Install Emacs
      run: sudo flatpak install -y https://dl.flathub.org/repo/appstream/org.gnu.emacs.flatpakref
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Build packages
      run: mkdir -p working && flatpak run org.gnu.emacs --batch -Q --script ./build.el
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'packages'
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
